# Generated by Django 5.1.7 on 2025-03-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamento_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
